import React, { Component, Fragment } from 'react'
import 'react-dropdown/style.css'
import { withRouter } from "react-router-dom";


class Terms extends Component {
  constructor(){
      super();
      this.state = {
        inputValue: 'yo',
      };
      
  }

  
  
  render() {
    return (
    <Fragment>
        <div class="page-banner-section terms-banner" style={{ marginTop : 50}}>
        <div class="wrapper">
            <div class="banner-inner">
                <h1 class="banner-heading">Terms Of Service</h1>
                <div class="heading-content-right">
                    <a href="https://www.netproreferral.com/" class="active">Home</a>
                    <span>&nbsp;&gt;&nbsp;</span>
                    <a>Terms Of Service</a>
                </div>
            </div>
        </div>
    </div>
    <section class="my-profile">
	<div class="wrapper">
		<div class="edit-profile-content-block">
			<div class="about-inner-main ad-abt-main">
								<div style={{ margin: 0 }} class="about-outer-main">
<div id="wrapper" style={{ textAlign : 'initial' }}>
<div class="about-inner-main">
<h4 style={{ color:' #00ccff'}}>TERMS OF SERVICE AGREEMENT</h4>
<p>This Terms of Service Agreement (the “<b>Agreement</b>”) is a legally binding contact between NetProReferral.com:, whose principal place of business is Insert Company Address (the “<b>Company</b>”), and any user (hereinafter referred to singularly and collectively as “<b>you</b>” or possessively as “<b>your</b>”) accessing, viewing or using Company’s software applications, systems, websites, methods and platforms (the “<b>Service</b>”).</p>
<p>Please read this Agreement carefully before accessing or using the Service. You must read, agree with and accept all of the terms and conditions contained in this Agreement, which includes those terms and conditions expressly set out below and those incorporated by reference, before you use any part of the Service. By using the Service, you expressly agree to be bound by this Agreement. Company is willing to license the Service to you for your use only upon the condition that you accept all the terms contained herein.</p>
<p>Your access to or use of the Service indicates that you have read, understood and consented to this Agreement and accept all of its associated terms. If you do not accept all of those conditions, Company is unwilling to license the Service for your use</p>
<p><span style={{ color:' #00ccff'}}><strong>The Service</strong></span></p>
<p>Company owns, maintains and provides the website located at http://www.netproreferral.com/, a service that connects professionals around the world and enables them to receive referrals from other users, generate leads and enhance their professional experience in a variety of ways. Insert Additional Marketing Information</p>
<p><span style={{ color:' #00ccff'}}><strong>Accounts</strong></span></p>
<p>The Service may require payment of a subscription fee for access and use. Features of the Service may be restricted to particular subscription tiers and you may be required to purchase an upgraded subscription to access or use a desired or particular feature.</p>
<p>To fully access and use the Service, you must first create a verified account and select a subscription, if applicable. If you purchase a subscription, the technical aspects and features of the Service you may access and use are defined and controlled by your selected subscription, including without limitation, connection, metric, transfer and other parameters. Exceeding such limits may result in your account being limited or restricted unless and until your subscription is upgraded. Company reserves the right to charge for any aspect of the Service, revise applicable subscription fees at any time and restrict the means and manner in which users can communicate with each other.</p>
<p>All payments will be facilitated either directly via Company’s payment processing system Company’s third-party payment processing service or an associated payment processor. Company may seek authorization of your credit card to validate your ability to pay any applicable charges prior to any purchase. If Company seeks such authorization, please note that the authorization is not a charge but may reduce your available credit by the authorization amount until your bank's next processing cycle.</p>
<p>It is your responsibility to determine what taxes apply to your use of the Service and collect, report and remit the correct amounts of tax to the appropriate tax authority, if applicable. Company is not responsible for determining whether taxes apply to your use of the Service or for collecting, reporting or remitting any taxes or any information related thereto arising out of or resulting from your use of the Service.</p>
<p>If a payment is subject to investigation by Company or a chargeback by the issuing bank, a hold will be placed on the payment and the account will be limited until such investigation or chargeback is resolved.</p>
<p>Company uses industry standard methods to protect the security of accounts and data from unauthorized access, use or disclosure. However, Company cannot fully defend against all potential security risks. You are solely responsible for maintaining the security of your account and routinely modifying your password to prevent unauthorized access. Accordingly, Company hereby disclaims, to the fullest extent of applicable law, any liability for unauthorized access, use or disclosure of your user account and assorted data.</p>
<p>You agree to Company’s collection, use, distribution, transmission, storage and retrieval of certain information concerning your use of the Service, including without limitation, technical, diagnostic or service level information that Company engineers and technicians may use to improve, enhance and upgrade the Service.</p>
<p><span style={{ color:' #00ccff'}}><strong>Term &amp; Termination</strong></span></p>
<p>This Agreement is effective immediately upon your access to or use of the Service for new users and upon the publishing date of any subsequent modifications, revisions or amendments for all current users. You may terminate your use of the Service at any time and for any reason upon our receipt of your notice of termination. Company may terminate your use of the Service without explanation.</p>
<p>If you would like for Company to delete your account and all information contained therein, you must provide notice to Company via email requesting that your account be cancelled and that all information contained therein be deleted. Upon receiving such request, Company will use commercially reasonable efforts to delete your information. Notwithstanding the foregoing, however, please note that your information may be retained on Company backup systems for some time. Company may terminate the Service, or any portion thereof, at any time and at its sole discretion.</p>
<p><span style={{ color:' #00ccff'}}><strong>User Information</strong></span></p>
<p>You may provide certain information to or via the Service, including information you use to register and create an account (collectively “<b>User Information</b>”). User Information will be stored on Company’s servers. You consent to such storage and Company’s use of User Information to create an account that will allow you to use the Service. You are solely responsible for User Information and hereby expressly acknowledge and agree that Company acts only as a passive conduit for such data.</p>
<p>When you use the Service, you agree to provide accurate, current and complete information and to maintain and keep it accurate, current and complete at all times. You agree that Company and third-parties may rely on User Information as accurate, current and complete. You acknowledge that if any information supplied by you is untrue, inaccurate, not current or incomplete in any respect, Company has the right to immediately terminate this Agreement and your use of the Service.</p>
<p>Upon termination, Company will remove all User Information from Company servers, though Company may retain an archived copy of records as required by applicable law or for legitimate business purposes. Company retains the right, in its sole and absolute discretion, to bar your use of the Service in the future for any or no reason. Following any such termination, this Agreement will remain in effect and any portions that, by their nature, survive termination, will survive and remain in full force and effect.</p>
<p>Company may examine User Information prior to, during or following receipt and, at its sole discretion, prevent, cease or reject transmission of inappropriate or otherwise inadequate or erroneous data. Company does not guarantee that User Information will be successfully transmitted to or received by Company. User Information or any other information or data transmitted or distributed via the Service does not reflect the views of Company and Company does not warrant the validity, reliability, accuracy, legality, suitability or current nature thereof.</p>
<p>The Service may allow messaging, communication and sharing tools to enable the transfer of information between users. Information transmitted with these tools may be accessible by other users, depending on the manner in which you send the communication. You acknowledge and agree that, if you use such tools, you accept all liability and consequences for the transmission.</p>
<p><span style={{ color:' #00ccff'}}><strong>Apps</strong></span></p>
<p>The following applies to applications accessed or downloaded via the Apple App Store (the “<b>App Store Sourced Application</b>”), a service owned and maintained by Apple, Inc. (“<b>Apple</b>”):</p>
<p>You acknowledge and agree that this Agreement is concluded between you and Company and Apple is a third-party beneficiary. You acknowledge and agree that Company, not Apple, is solely responsible for the App Store Sourced Application and all content thereof.</p>
<p>Your use of the App Store Sourced Application must comply with the App Store Terms of Service. You acknowledge that Apple has no obligation whatsoever to furnish maintenance and support services with respect to the App Store Sourced Application.</p>
<p>In the event of failure of the App Store Sourced Application to conform to any applicable warranty, you may notify Apple which may, in its sole discretion, refund the purchase price and, to the maximum extent permitted by applicable law, Apple will have no other obligation or liability whatsoever with respect to the App Store Sourced Application. As between Company and Apple, any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be the sole responsibility of Company.</p>
<p>Apple is not responsible for addressing your or third-party claims arising out of or relating to the App Store Sourced Application or your possession and use thereof, including without limitation, product liability claims, claims that the App Store Sourced Application fails to conform to applicable legal or regulatory requirements and claims arising under consumer or customer protection legislation.</p>
<p>In the event of third-party claims that the App Store Sourced Application or your possession and use thereof infringes a third-party’s intellectual property rights, Company, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of such claim to the extent required under the terms and conditions hereof.</p>
<p>Upon your acceptance of the terms and conditions of this Agreement, Apple will have the right, and will be deemed to have accepted the right, to enforce this Agreement as related to your license to use the App Store Sourced Application as a third-party beneficiary. You must comply with all applicable Apple and third-party terms of agreement when using the App Store Sourced Application.</p>
<p>The following applies to applications accessed or downloaded via the Google Play Store (the “<b>Google Play Sourced Application</b>”):</p>
<p>You must be thirteen (13) years of age or older to use the Google Play Sourced Application. If you are between thirteen (13) and eighteen (18) years of age, you must have your parent or guardian’s permission to use the Google Play Sourced Application. You must not access the Google Play Sourced Application if you are barred or otherwise legally prohibited from the receipt or use thereof under the laws of the country in which you reside or from which you access the Google Play Sourced Application.</p>
<p>You will need a Google Wallet account to purchase the Google Play Sourced Application. The Google Wallet Terms of Service and Privacy Notice apply to all purchases of a Google Play Sourced Application. Notwithstanding the foregoing, however, you may be required to transact with the Google Play Sourced Application provider directly.</p>
<p><span style={{ color:' #00ccff'}}><strong>Third-Party Services</strong></span></p>
<p>As part of the functionality of the Service, you may be able use certain third-party services (each a “<b>Third-Party Service</b>” and, collectively, the “<b>Third-Party Services</b>”). Unless otherwise specified herein, any content you provide to or store with any Third-Party Service is beyond the control of Company and Company cannot and will not be liable for any use of User Information you submit to any Third-Party Service.</p>
<p><b>Your relationship with Third-Party Services is governed solely by the applicable contractual agreement between you and the Third-Party.</b></p>
<p>Company makes no effort to review content provided to Third-Party Services or contractual agreements you execute therewith for any purpose, including without limitation, accuracy, legality or non-infringement. Company is not responsible in any way for your interaction with any third-party or Third-Party Service.</p>
<p><span style={{ color:' #00ccff'}}><strong>Representations &amp; Warranties</strong></span></p>
<p>By using the Service, you expressly represent and warrant that you are legally entitled to enter this Agreement. If you reside in a jurisdiction that restricts the use of the Service because of age or restricts the ability to enter into agreements such as this one due to age, you must abide by such age limits and must not use the Service. Without limiting the foregoing, the Service is not available to persons under eighteen (18) years of age. By using the Service, you represent and warrant that you are at least eighteen (18) years old and have never been nor are currently a “Specially Designated National” or other person to whom the Service is prohibited. By using the Service, you represent and warrant that you have the right, authority and capacity to enter into this Agreement and will abide by its terms and conditions. Your participation in using the Service is for your sole personal use. You may not authorize others to use your account and may not assign or otherwise transfer your account to any third-party. You agree to comply with all applicable local, state, national and international laws and regulations.</p>
<p>You may only access the Service using authorized means. It is your responsibility to ensure adequate access to the Internet and requisite capacity to use the Service. Further, it is your responsibility to ensure you have downloaded the correct version of applications necessary to use of the Service, if applicable. Company is not liable if you do not have compatible connections, devices or applications or if you have downloaded incorrect or erroneous versions of software or materials containing viruses or other harmful data or instructions. Company reserves the right to terminate this Agreement should you use the Service with an incompatible or unauthorized connection, device or application.</p>
<p>You agree and warrant that you will not:</p>
<ul class="termul">
<li>use the Service for any unlawful purpose;</li>
<li>use the Service for sending or storing unlawful material or to engage in fraudulent activities or a fraudulent purpose;</li>
<li>use the Service to cause nuisance or inconvenience;</li>
<li>impair the proper operation of any network;</li>
<li>harm or attempt to harm the Service, Company or third-parties;</li>
<li>copy or distribute the Service;</li>
<li>use the Service for any use except your own and will not resell or attempt to resell any part of the Service to any third-party;</li>
<li>provide false information or identification evidence;</li>
<li>use unauthorized Wi-Fi access points or mobile data accounts;</li>
<li>imply or state, directly or indirectly, that you are affiliated with or endorsed by Company without express written permission;</li>
<li>use the Service to impersonate another person;</li>
<li>send messages using the Service which do not correctly identify the sender and will not alter the attribution of origin in email messages or postings;</li>
<li>transmit content, nor a link to any content, that is pornographic, sexually explicit, obscene or violent;</li>
<li>breach this Agreement, card processing or other agreements you have entered into with Company or third-parties;</li>
<li>violate laws, statutes, ordinances or regulations, including without limitation, those governing safety, health, medical records, financial services, consumer protection, unfair competition, anti-discrimination or false advertising;</li>
<li>act in a manner that is defamatory, libelous or harassing;</li>
<li>create more than one user account, nor use a name that is not yours or any temporary email address or phone number or other false information;</li>
<li>send or receive fraudulent or potentially fraudulent funds;</li>
<li>use any mechanism to mask your identity or location;</li>
<li>control or possess more than one account; nor</li>
<li>cause to attempt to cause complaints, disputes, claims, chargebacks, fees, penalties or other liability.</li>
</ul>
<br />
<p><span style={{ color:' #00ccff'}}><strong>Intellectual Property</strong></span></p>
<p>Company owns and retains ownership in the Service and all associated intellectual property rights contained therein. Contingent on your compliance with, and subject to, the terms and conditions of this Agreement, Company grants you a limited, non-transferable, non-exclusive, non-assignable, revocable license to use the Service on any device that you own or control and as permitted by the Usage Rules set forth in Section 9(b) of the Apple App Store Terms and Conditions (the “<b>Usage Rules</b>”), if applicable. No licenses or rights are granted to you, by implication or otherwise, to any intellectual property rights owned or controlled by Company or its licensors, except for the licenses and rights expressly granted hereunder.</p>
<p>The terms of the license granted to you herein will govern upgrades provided by Company that replace or supplement the Service, unless such upgrade is accompanied by a separate license in which case the terms of such license will govern.</p>
<p>You agree and warrant that you will not:</p>
<ul class="termul">
<li>license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third-party the Service in any way;</li>
<li>modify or make derivative works based upon the Service;</li>
<li>create "links" to the Service, "frame" or "mirror" any part thereof on any server, wireless or Internet device;</li>
<li>use, copy, adapt, modify, prepare derivative works of, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or exploit the Service;</li>
<li>reverse engineer the Service;</li>
<li>build a competitive product or service;</li>
<li>build a product using ideas or features similar to the Service;</li>
<li>copy ideas or features of the Service or launch an automated program or script, including without limitation, spiders, crawlers, robots, bots, ants, indexers, viruses, worms or any program which make multiple server requests or unduly burden the operation of the Service;</li>
<li>send spam or unsolicited messages;</li>
<li>send or store infringing, obscene, threatening, libelous, unlawful or tortious material, including without limitation, material harmful to children or in violation of privacy rights;</li>
<li>send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs;</li>
<li>interfere with or disrupt the integrity or performance of the Service or data contained therein; nor</li>
<li>attempt to gain unauthorized access to the Service.</li>
</ul>
<p><b>Any of the foregoing is a violation of Company’s valuable and proprietary rights that may subject you to prosecution and civil damages. Company will fully investigate and prosecute any such actions to the fullest extent of the law and may involve and cooperate with law enforcement authorities.</b></p>
<p>You acknowledge that Company has no obligation to monitor your access to or use of the Service or to review or edit any User Information or other data you transmit or submit to the Service, but has the right to do so for the purpose of operating the Service, to ensure your compliance with this Agreement or to comply with applicable law or the order of a court, administrative agency or other governmental body. Company reserves the right to remove or disable access, at any time and without notice, to any information that Company deems to be in violation of this Agreement or otherwise harmful to the Service or third-parties.</p>
<p>By transmitting or submitting User Information or other data to the Service, you thereby grant to Company a worldwide, irrevocable, perpetual, non-exclusive, transferable, royalty-free license, with the right to sublicense, to use, view, copy, adapt, modify, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast and otherwise exploit such content on, through or by means of the Service. Company does not claim any ownership rights in such content and nothing in this Agreement will be deemed to restrict any rights you may have to use and exploit any portion thereof.</p>
<p>You acknowledge and agree that you are solely responsible for content you make available through the Service. You represent and warrant that you are either the sole and exclusive owner of all such content or have all rights, licenses, consents and releases necessary to grant a license to Company to use such content and neither the content nor the posting, uploading, publication, submission, transmittal nor Company’s use thereof will infringe, misappropriate or violate any third-party’s patent, copyright, trademark, trade secret, moral, publicity, privacy or other rights or result in the violation of applicable laws or regulations.</p>
<p>Company respects copyright law and expects you to do the same. Company will terminate, in its sole discretion, user accounts that infringe, or are believed to be infringing, the rights of copyright holders.</p>
<p>Pursuant to the Digital Millennium Copyright Act (the “<b>DMCA</b>”), Company will review and promptly act upon all notices of copyright infringement. If you are a copyright holder and believe that material contained within the Service violates your intellectual property rights, please contact Company’s copyright agent at dmca@netproreferral.com. Any copyright notice transmitted to Company must include all of the following information: an electronic or physical signature of a person authorized to act on behalf of the copyright owner; identification of the copyrighted work claimed to be infringed; identification of the material claimed to be infringing and the exact location of such material within the Service; information reasonably sufficient to permit Company to contact you, such as physical address, telephone number or email address; a statement that you have a good faith belief that use of the material in the stated manner is not authorized by the copyright owner, its agent or the law; and a statement, made under penalty of perjury, that you are the copyright owner or authorized to act on the copyright owner’s behalf.</p>
<p>Company and its licensors retain and own all right, title and interest, including without limitation, intellectual property rights, in the Service and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the Service. This Agreement is not a sale nor a license and does not convey any rights of ownership or license rights relating to the Service or any intellectual property rights owned by Company. The Company name, logo and product names associated with the Service are trademarks of Company and no right or license thereto is granted nor contemplated by this Agreement.</p>
<p><span style={{ color:' #00ccff'}}><strong>Communications</strong></span></p>
<p>Email communications and text messages sent by Company are designed to make your professional experience more efficient and productive. By accepting the terms of this Agreement, you explicitly consent to receive email communications, text messages and other transmissions initiated by Company, including without limitation, notifications, communications informing you about potential services, promotions, new or existing features and professional referrals or communications from other users of the Service. Standard text messaging rates charged by your mobile phone carrier will apply to text messages sent by Company, if applicable. If you change your mobile carrier, notifications and communications may be deactivated for your user account and you will be required to reauthorize your new mobile phone number for such messages. Company reserves the right to cancel notifications and communications at any time without notice.</p>
<p><span style={{ color:' #00ccff'}}><strong>Indemnification</strong></span></p>
<p>You will defend, indemnify and hold Company, its officers, directors, employees, agents and any associated third-parties harmless for any losses, costs, liabilities and expenses, including reasonable attorney fees, arising out of or relating to your use of the Service, including without limitation, your breach of this Agreement or the documents it incorporates by reference; your violation of any law or the rights of any third-party; any allegation that any materials that you submit to Company or transmit via the Service infringe or otherwise violate the copyright, trademark, trade secret or other intellectual property or other rights of any third-party; and any other activities in connection with your use of the Service. This indemnity will be applicable without regard to the negligence of any party, including any indemnified person, Company or third-parties with whom Company does business.</p>
<p><span style={{ color:' #00ccff'}}><strong>Disclaimer of Warranties</strong></span></p>
<p>COMPANY MAKES NO REPRESENTATION OR WARRANTY AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, AVAILABILITY, ACCURACY OR COMPLETENESS OF THE SERVICE. COMPANY DOES NOT REPRESENT OR WARRANT THAT:</p>
<ul class="termul">
<li>USE OF THE SERVICE WILL BE SECURE, TIMELY, UNINTERRUPTED, ERROR-FREE OR OPERATE WITH OTHER HARDWARE, APPLICATIONS, SYSTEMS OR DATA;</li>
<li>THE SERVICE WILL MEET REQUIREMENTS;</li>
<li>ANY STORED DATA WILL BE ACCURATE OR RELIABLE;</li>
<li>THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL PURCHASED OR OBTAINED BY THE USER THROUGH THE SERVICE WILL MEET USER REQUIREMENTS OR EXPECTATIONS;</li>
<li>ERRORS IN THE SERVICE WILL BE CORRECTED;</li>
<li>THE SERVICE, EQUIPMENT OR SERVER THAT MAKE THE SERVICE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS;</li>
<li>THE SERVICE WILL PROVIDE TIMELY, USEFUL OR SUCCESSFUL REFERRALS FROM OTHER USERS; OR
<p>REFERRALS WILL IN ANY WAY PRODUCE OR GENERATE BUSINESS, OPPORTUNITIES, ACTUAL REFERRALS OR INCOME FOR YOU.</p>
</li>
</ul>
<p><b>THE SERVICE IS PROVIDED ON AN “AS IS” BASIS. ALL CONDITIONS, REPRESENTATIONS AND WARRANTIES, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE DISCLAIMED TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.</b></p>
<p>COMPANY MAKES NO REPRESENTATION, WARRANTY OR GUARANTY AS TO THE RELIABILITY, SAFETY, TIMELINESS, QUALITY, SUITABILITY OR AVAILABILITY OF THE SERVICE NOR ANY SERVICES OR PRODUCTS OBTAINED BY THIRD-PARTIES VIA THE SERVICE. YOU ACKNOWLEDGE AND AGREE THAT THE ENTIRE RISK ARISING OUT YOUR USE OF THE SERVICE OR ANY THIRD-PARTY SERVICES OR PRODUCTS REMAINS SOLELY WITH YOU TO THE MAXIMUM EXTENT PERMITTED BY LAW.</p>
<p>THE SERVICE MAY BE SUBJECT TO LIMITATIONS, DELAYS AND PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS. COMPANY IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES OR DAMAGES RESULTING THEREFROM.</p>
<p><span style={{ color:' #00ccff'}}><strong>Limitation of Liability</strong></span></p>
<p>IN NO EVENT WILL COMPANY BE LIABLE TO ANYONE FOR INDIRECT, PUNITIVE, SPECIAL, EXEMPLARY, INCIDENTAL, CONSEQUENTIAL OR OTHER DAMAGES OF ANY TYPE OR KIND, INCLUDING WITHOUT LIMITATION, PERSONAL INJURY, LOSS OF DATA, REVENUE, PROFITS, USE OR OTHER LOSS OF ECONOMIC ADVANTAGE OR BENEFITS. COMPANY WILL NOT BE LIABLE FOR ANY LOSS, CLAIM, DAMAGES OR INJURIES WHICH MAY BE INCURRED DUE TO USE OF THE SERVICE, INCLUDING WITHOUT LIMITATION DAMAGES OR INJURIES ARISING OUT OF OR IN ANY WAY CONNECTED WITH OR RESULTING FROM THE SERVICE, PRODUCTS OR SERVICES AVAILABLE VIA THE SERVICE, USE OR INABILITY TO USE THE SERVICE, RELIANCE PLACED BY THE USER ON COMPLETENESS, ACCURACY OR EXISTENCE OF ANY ADVERTISING OR INFORMATION CONTAINED WITHIN THE SERVICE OR RESULTING FROM ANY RELATIONSHIP BETWEEN YOU AND THIRD-PARTY SERVICES, PRODUCTS, ADVERTISERS OR SPONSORS, EVEN IF COMPANY OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
<p>COMPANY MAY INTRODUCE YOU TO OTHER USERS OR THIRD-PARTIES FOR PURPOSES OF PROVIDING ACCESS TO THIRD-PARTY SERVICES OR RECEIVING PROFESSIONAL REFERRALS. COMPANY WILL NOT ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF ANY THIRD-PARTY OR THIRD-PARTY SERVICE AND YOU HEREBY EXPRESSLY WAIVE, RELEASE AND FOREVER DISCHARGE COMPANY FROM ALL LIABILITY, CLAIMS, DAMAGES AND INJURIES ARISING OUT OF OR IN ANY WAY CONNECTED WTIH OR RESULTING FROM THE SERVICE, THIRD-PARTIES AND THIRD-PARTY SERVICES. YOU ACKNOWLEDGE THAT OTHER USERS OR THIRD-PARTY SERVICES MAY NOT BE PROFESSIONALLY LICENSED OR PERMITTED. COMPANY WILL NOT BE A PARTY TO DISPUTES, NEGOTIATIONS OF DISPUTES, LITIGATION, MEDIATION OR ARBITRATION BETWEEN YOU AND OTHER USERS OR THIRD-PARTIES. COMPANY CANNOT AND WILL NOT PLAY ANY ROLE IN MANAGING PAYMENTS BETWEEN YOU AND OTHER USERS OR THIRD-PARTIES. RESPONSIBILITY FOR DECISIONS YOU MAKE REGARDING THE SERVICE, OTHER USERS, POTENTIAL OR ACTUAL REFERRALS AND THIRD-PARTY SERVICES, WITH ALL ASSOCIATED IMPLICATIONS AND CONSEQUENCES, REST SOLELY WITH YOU. COMPANY WILL NOT ASSESS THE LEGALITY, LIABILITY OR ABILITY OF THIRD-PARTIES RESULTING FROM ANY NEGLIGENCE, CLAIMED OR OTHERWISE, NOR ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF THIRD-PARTIES TO PAY DAMAGES RESULTING THEREFROM AND YOU HEREBY EXPRESSLY WAIVE, RELEASE AND FOREVER DISCHARGE COMPANY FROM ALL LIABILITY, CLAIMS, CAUSES OF ACTION, DAMAGES AND INJURIES ARISING OUT OF OR IN ANY WAY CONNECTED WTIH OR RESULTING FROM THE SERVICE, USE OF THE SERVICE OR OTHER USERS, THIRD-PARTIES OR THIRD-PARTY SERVICES INTRODUCED TO YOU BY THE SERVICE OR COMPANY. YOU EXPRESSLY WAIVE AND RELEASE ALL RIGHTS AND BENEFITS UNDER SECTION 1542 OF THE CIVIL CODE OF THE STATE OF CALIFORNIA (OR ANY ANALOGOUS LAW OF ANY OTHER STATE OR COUNTRY), WHICH READS AS FOLLOWS: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM, MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.”</p>
<p>QUALITY OF SERVICE IS THE SOLE RESPONSIBILITY OF THE THIRD-PARTY THAT ULTIMATELY PROVIDES THE SERVICE. YOU UNDERSTAND, ACKNOWLEDGE AND AGREE THAT, BY USING THE SERVICE OR RECEIVING REFERRALS FROM OTHER USERS, YOU MAY BE EXPOSED TO PRODUCTS, SERVICES OR INDIVIDUALS THAT ARE POTENTIALLY DANGEROUS, INJURIOUS, PHYSICALLY DISABLING OR CHALLENGING, OFFENSIVE, HARMFUL TO MINORS, UNSAFE OR OTHERWISE OBJECTIONABLE AND YOU USE THE SERVICE AT YOUR OWN RISK.</p>
<p><span style={{ color:' #00ccff'}}><strong>Notice</strong></span></p>
<p>Company may give notice via the Service, email to your email address or written communication sent by pre-paid mail to your address.</p>
<p><span style={{ color:' #00ccff'}}><strong>Assignment</strong></span></p>
<p>This Agreement may not be assigned by you but may be assigned, without notice nor consent, by Company to a parent company, subsidiary, acquirer of assets or successor by merger. Any purported assignment in violation of this provision will be void.</p>
<p><span style={{ color:' #00ccff'}}><strong>Export Control</strong></span></p>
<p>You agree to fully comply with all applicable export laws and regulations to ensure neither the Service, technical data related thereto nor product thereof is exported or re-exported, directly or indirectly, in violation of or used for any purpose prohibited by such laws and regulations. By using the Service, you represent and warrant that you are not located in a country subject to government embargo or designated by any government as a “terrorist supporting” country and are not listed on any government list of prohibited or restricted jurisdictions.</p>
<p><span style={{ color:' #00ccff'}}><strong>Dispute Resolution</strong></span></p>
<p>You agree that any dispute, claim or controversy arising out of or relating to this Agreement, the breach, termination, enforcement, interpretation or validity thereof (collectively, the “<b>Disputes</b>”) will be settled by binding arbitration, except that each Party retains the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a Party’s copyrights, trademarks, trade secrets, patents or other intellectual property rights. The Parties waive the right to a trial by jury or to participate as a plaintiff or in any purported class action or representative proceeding. Unless otherwise explicitly agreed in writing, any arbitrator operating pursuant to this provision may not consolidate more than one Party’s claims and may not otherwise preside over any form of any class or representative proceeding. The provision and requirement that Disputes be settled by binding arbitration will survive termination.</p>
<p>Unless the Parties otherwise explicitly agree in writing, the arbitration will be conducted in the city where Company is located and be based solely on the basis of documents submitted to the arbitrator, unless a hearing is requested or the arbitrator determines a hearing is necessary. The arbitrator will have discretion to direct a reasonable exchange of information between the Parties concerning Disputes.</p>
<p>The arbitrator’s decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction. The arbitrator’s award damages must be consistent with the terms and conditions hereof regarding the type and amount of damages for which a Party may be held liable. The arbitrator may award declaratory or injunctive relief only in favor of the claimant and only to the extent necessary to provide relief warranted by the claimant’s individual claim. Any Party that prevails in arbitration will be entitled to an award of attorney fees and expenses, to the extent provided under applicable law.</p>
<p><span style={{ color:' #00ccff'}}><strong>General Provisions</strong></span></p>
<p>No joint venture, partnership, employment or agency relationship exists between you, Company or any third-party as a result of this Agreement or your use of the Service. If any provision of this Agreement is held invalid or unenforceable, such provision will be stricken from the text and the remaining provisions will be enforced to the fullest extent of applicable law. The failure of Company to enforce any right or provision herein will not constitute a waiver of such right or provision unless explicitly acknowledged and agreed to by Company in writing. Company will not be liable for delay or failure in its performance or any damages suffered by you due to such delay or failure, caused by or resulting from, directly or indirectly, natural acts or events beyond Company’s control. This Agreement constitutes the entire agreement between the Parties and supersedes all prior or contemporaneous negotiations, discussions or agreements, whether written or oral, regarding the subject matter hereof. The laws of Insert Jurisdiction will govern this Agreement and Disputes arising hereunder will be adjudicated in the courts therein.</p>
<p>Effective Date: July 21, 2016.</p>

</div>
</div>
</div>			</div>
		</div>
	</div>
</section>
</Fragment>
    )
  }
}

Terms.propTypes = {}

Terms.defaultProps = {}

export default withRouter(Terms)
